var diccionario = [
    ["",""],
    ["Antier","Día anterior al de ayer, antes de ayer."],
    ["Egolatría","Culto y veneración que una persona se profesa a sí mismo."],
    ["Criollo","Que es característico de la cultura y la tradición de un país hispanoamericano."],
    ["Larvado","Que está muy escondido, reservado y oculto."],
    ["Recóndita","Es el efecto de la luz del Sol al proyectarse sobre las nubes matutinas y de la tarde, que les otorga tonalidades rojizas"],
    ["Elucubración","Pensamiento o reflexión sobre algo conseguido tras un intenso trabajo intelectual."],
    ["Racha","Periodo de tiempo corto de buena o mala suerte, (período breve de fortuna o desgracia)."],
    [" Ignoto","Que es desconocido o que no ha sido descubierto."],
    ["Histrión","Persona que habla o actúa haciendo gestos de manera exagerada y marcando excesivamente su expresión."],
    ["Disensión","Falta de acuerdo o de aceptación, por parte de una persona, de una situación, una decisión o una opinión."],
    ["Díada","Pareja de dos principios o seres estrechamente vinculados entre sí."],
    ["Dilogía","Figura retórica que consiste en emplear una palabra en un enunciado con dos significados simultáneos."],
    ["Disenso","Conformidad de las partes en disolver o dejar sin efecto el contrato u obligación entre ellas existente."],
    ["Divieso","Tumor puntiagudo y duro que se forma en el espesor de la piel por inflamación de un folículo sebáceo."],
    ["Cenotafio","Monumento funerario que no contiene el cadáver del personaje a quien se dedica."],
    ["Longevidad","Cualidad de la persona que vive muchos años."],
    ["Lúgubre","Que es profundamente triste y sombrío."],
    ["Tétrico","Que es muy oscuro, triste y grave, y hace pensar en la muerte."],
    ["Menester","Falta o necesidad de una cosa."],
    ["Ostentar","Exhibir abiertamente y con orgullo una cosa."],
    ["Neófito","Persona que acaba de unirse a una opinión o una causa, o que se acaba de incorporar a un grupo o colectividad."],
    ["Moraleja","Enseñanza que se extrae de un cuento, una fábula o un suceso de la vida."],
    ["Mundano","Propio del ambiente de la alta sociedad."],
    ["Mero","Que es puro, sin mezcla, sin ninguna característica particular."],
    ["ACÚSTICA","Estudio de la propagación del sonido"],
    ["AGRADAR","Cualidad que consiste en hablar o escribir con gracia y buen gusto, es decir, de manera atrayente, persuasiva, conmovedora, correcta, proporcional, coherente, clara, elegante, concisa y armoniosa."],
    ["ALOCUCIÓN","Discurso, razonamiento o tema, por lo común breve, que un superior dirige a sus subordinados, inferiores, secuaces o súbditos."],
    ["AMBIGÜEDAD"," Un estilo es ambiguo cuando presenta los asuntos de manera que puede entenderse de más de una manera."],
    ["APÓCOPE","Supresión o corte de un sonido al final de una palabra. Ej. Radio por radiodifusión. Primer por primero. Ma por mamá. Auto por automóvil."],
    ["APRENDIZAJE","Adquirir por la práctica una conducta duradera. La mayoría de lo que conocemos del idioma la aprendemos por instinto, escuchando a los demás."],
    ["ASTEÍSMO","Ironía caracterizada por una graciosa y delicada alabanza en forma de reprensión"],
    ["ASTRONÓMICO"," Algo desmesuradamente grande."],
    ["BIMEMBRE","Dos miembros. Oración de dos miembros o elementos: SUJETO y PREDICADO."],
    ["CACOFONÍA","Sonido desagradable que resulta de una combinación inarmónica de las palabras de una frase u oración."],
    ["CIMENTA","“Se cimenta en”, “se apoya o fundamenta en”"],
    ["COACTAR.","Esta palabra no aparece en el diccionario de la Academia. Por lo tanto, la expresión culta es: Ejercer coacción, de coacción, que significa, en este contexto, obligar o imponer por la fuerza. No es lo mismo que coartar."],
    ["CONFIRMACIÓN","Sección de la redacción del tema que corresponde al desarrollo del tema o argumento. Sirve para presentar las razones, motivos, pruebas, evidencias, testimonios, referencias y demás elementos de juicio para que el lector tome una decisión."],
    ["CONSIDERACIÓN","Pensar en alguien reflexionando con atención y cuidado respecto a su valor como ser humano, su situación en la vida y el efecto que sus acciones tienen en la comunidad."],
    ["COOPERATIVISMO","Relación, actividad o estudio basados en la cooperación, en hacer las cosas juntos (La competitividad es opuesta y se basa en el fracaso de los demás, en que uno solo gana)."],
    ["COORDINACIÓN","Relación que existe entre las palabras de una oración."],
    ["CORTAPISA","Condición o restricción con que se concede o posee algo."],
    ["CORTESÍA","Demostración liberal y gratis de interés y servicio que brota de un sentimiento de nobleza hacia otra persona."],
    ["DEFERENCIA","Sentimiento de aprecio que impulsa a uno a tener en cuenta a otra persona por medio de adaptarse y acomodarse a sus gustos y deseos"],
    ["DEFINICIÓN","Aclaración exacta de las características de algo."],
    ["DIACRÓNICO","A lo largo del tiempo o en un período. Opuesto a sincrónico, que se refiere a algo que ocurre temporalmente o en un momento dado."],
    ["DOGMA","Declaración, enseñanza o doctrina que alguien impone y otros aceptan y obedecen inconcusamente, aunque no medie discusión ni réplica alguna ni nada que pruebe, apoye o respalde su veracidad."],
    ["DRAMÁTICO","Teatral, afectado, con el fin de conmover profundamente."],
    ["ÉGLOGA","Redacción de estilo poético que generalmente se refiere al ideal de la vida campestre."],
    ["ENFOQUE COGNITIVO","El enfoque psicológico cognitivo estudia a las personas que cometen errores sistemáticamente, por lo general graves, cuando toman decisiones."],
    ["ENLACE","Conexión armoniosa entre los elementos de la oración y la redacción."],
    ["ENTORNO"," Es el ambiente o lo que rodea al redactor o protagonista de un relato."],
    ["EPÍLOGO","Parte de la peroración o conclusión de la redacción del tema cuyo objetivo es resumir las conclusiones a que se ha llegado en el desarrollo o confirmación."],
    ["ESDRÚJULA","Palabra que lleva el acento en la antepenúltima sílaba."],
    ["ESPAÑOL","Lengua común de los españoles, exenta de particularidades regionales."],
    ["ESTÁTICO","Que permanece en un mismo estado, sin cambiar."],
    ["ESTÉTICA","Armonía y apariencia de una cosa desde el punto de vista de lo que se considera bello y elegante."],
    ["ESTULTICIA","Necedad, tontería. “El Elogio de la Estulticia” significa “la alabanza de la tontería”"],
    ["ETOPEYA"," Redacción que presenta el carácter, acciones y costumbres de una persona."],
    ["EUFONÍA","Parte de la retórica que trata de la estética de los efectos sonoros del lenguaje, la combinación armoniosa de los sonidos de la lengua."],
    ["EXHORTACIÓN","Advertencia o aviso persuasivo"],
    ["EXORDIO","Introducción de un tema, generalmente para captar la atención y despertar el interés del auditorio."],
    ["EXORDIO ABRUPTO","Modalidad básica  de introducción de una redacción que va directamente al punto y sin rodeos."],
    ["FONÉTICA","Ciencia que estudia el sonido y la acústica de un idioma."],
    ["FONOLOGÍA","Estudio de los fonemas o sonidos ideales, infinitos, que conforman la lengua en general, es decir, con todas sus variantes."],
    ["FÓRMULA","Medio práctico diseñado para resolver un asunto difícil."],
    ["FORO","Lugar o punto de reunión donde se discuten asuntos de interés actual ante un auditorio que a veces interviene en persona, por carta o teléfono con preguntas, respuestas o comentarios."],
    ["FRASE","Frase es un conjunto de palabras que basta para formar un sentido. En gramática se prefiere el nombre de oración."],
    ["GARRAFAL","Falta grave cometida contra un reglamento o tradición."],
    ["GRITO","Voz muy alzada, generalmente como manifestación vehemente."],
    ["GUION"," Contenido detallado de una obra cinematográfica o de la manera como se debe llevar a cabo un objetivo."],
    ["IMPLÍCITO","Algo que está incluido, aunque no expresado, como el sujeto implícito."],
    ["ÍNDEX"," Índice general o lista ordenada del contenido de un archivo."],
    ["INICIATIVA","Hacer algo antes que los demás y sin que otro lo haya sugerido."],
    ["INTERNET"," Autopista informática mundial por computadora."],
    ["IRONÍA","Contradicción ridícula o disimulada que generalmente se expresa en tono de burla."],
    ["LLAMADA","Señal que dirige la atención a otro lugar de un escrito, como una referencia o nota al pie de página, o hipervínculo."],
    ["LOCUTOR","Persona que habla por el micrófono en las estaciones de radio."],
    ["MELODÍA","Propiedad musical de las palabras, sea que se canten mentalmente o con la voz o por escrito."],
    ["MORFOLOGÍA","Análisis de la forma de los elementos de la oración"],
    ["MORFOSINTÁXIS","La sintaxis analiza la función de los elementos de la oración, y la morfología estudia su forma, pero su constante y mutua dependencia dio lugar a la morfosintaxis o el estudio de ambas cosas."]
]
var inputText = document.getElementById("busca").addEventListener("keyup",function(){
    var texto = this.value;
    document.getElementById("definir").innerHTML="";
    texto = texto.toUpperCase();
    var regEx = RegExp(texto,"g");
    for(var i=0;i<diccionario.length;i++){
        if(regEx.test(diccionario[i][0].toUpperCase())){
            document.getElementById("definir").innerHTML=diccionario[i][1];
            break;
        }else{
            document.getElementById("definir").innerHTML="";
        }
    }
});